### ISSUE TITLE
for constants.py, no need for BATCH_NUM_TRIPLETS to be a multiple of 3

### ISSUE THREAD

**Issue by XingyuGuUCSD** [philipperemy/deep-speaker#17]
BATCH_NUM_TRIPLETS = 6  # should be a multiple of 3

no need to be a multiple of 3

**Comment by Charliechen1** [comment]
Agree, BATCH_NUM_TRIPLETS should be the number of triplets.

**Comment by philipperemy** [comment]
Try again with the new master. I pushed the latest code. This issue is not relevant anymore.
