### ISSUE TITLE
How can I make prediction for one audio file.

### ISSUE THREAD

**Issue by Charliechen1** [philipperemy/deep-speaker#20]
From your source code, it seems the file to predict should also be packed into batches the same size as when training. What if I have just one file and I wanna make the vector for it alone? How shall it be done. Thank you.

**Comment by philipperemy** [comment]
@Charliechen1 check the latest master.

Everything is now explained. This is still alpha work. I'll continue working on this for the next upcoming weeks.

https://github.com/philipperemy/deep-speaker/blob/master/README.md
