### ISSUE TITLE
missing pkl files for testing

### ISSUE THREAD

**Issue by prashantmaheshwari94** [philipperemy/deep-speaker#21]
Hi @philipperemy ,

Thanks you for the implementation. Can you help us with the files - speaker-change-detection-norm.pkl and speaker-change-detection-categorical_speakers.pkl. I couldn't find this resource on repo. Also, can you guide how the trained model can be used for inference?

Cheers!

**Comment by prashantmaheshwari94** [comment]
Hi @philipperemy
I was able to generate those files. However, I am not sure of two things
1. How I can inference on trained model for any audio.
2. What network you used for generating embedings.
If you could help, it would great.

Cheers!

**Comment by philipperemy** [comment]
@prashantmaheshwari94 for now there's no easy way to make inference. The deep speaker task is pretty difficult! You can make some inference based on the speakers of the VCTK corpus dataset.

**Comment by prashantmaheshwari94** [comment]
@philipperemy Okay. So I will have to generate pickle file for VCTK dataset using "generate_inputs.py" and then pass it as input to some modified version of "test_with_unseen_speakers.py" script?

**Comment by philipperemy** [comment]
Something like that. I have to dig into that again. I'll probably look at it this end of week!

**Comment by prashantmaheshwari94** [comment]
Okay. Do share the methodology. I can try doing it on my end.

**Comment by philipperemy** [comment]
Thanks I will!

**Comment by prashantmaheshwari94** [comment]
hey, Is there any update on this?

**Comment by philipperemy** [comment]
@prashantmaheshwari94 now having a look. It will take me some time but I hope to complete it for end of next week!

**Comment by philipperemy** [comment]
@prashantmaheshwari94 been working on it for those past 3 days.

It's in master now. https://github.com/philipperemy/deep-speaker/blob/master/README.md

Have a look and tell me. It's still very alpha work. But I could get it working here.

**Comment by philipperemy** [comment]
I'll be still working on it to improve it and add all the files

**Comment by prashantmaheshwari94** [comment]
@philipperemy thanks for the implementation. I will have a look at it today.

**Comment by prashantmaheshwari94** [comment]
@philipperemy it worked like a charm. Thanks for the great implementation.
I was thinking of running it to compute accuracy on some standard dataset.

**Comment by philipperemy** [comment]
@prashantmaheshwari94 great! Happy to hear that!

**Comment by philipperemy** [comment]
I'll close this issue for now. Let me know how it goes!
