### ISSUE TITLE
Dimensions issue

### ISSUE THREAD

**Issue by NightFury10497** [philipperemy/deep-speaker#23]
![image](https://user-images.githubusercontent.com/30961652/46903993-1b9a2480-cefb-11e8-824d-77a38cc8b477.png)

**Comment by zhangshyang** [comment]
I meet the same problem. I try to delete the chechpoints document, and the xx.h5 is not existed. The code can be run. So you can have a try.

**Comment by NightFury10497** [comment]
how will i delete checkpoint while it is getting compiled

**Comment by philipperemy** [comment]
@NightFury10497 no checkpoints dont get deleted unless you remove them with `rm`.

**Comment by philipperemy** [comment]
Can you provide the commands that triggered this error @NightFury10497 ?

**Comment by MingruiYuan** [comment]
Hello, I met the same problem. The two commands are as follows:
1) python cli.py --regenerate_full_cache --multi_threading --cache_output_dir $CACHE_DIR --audio_dir $AUDIO_DIR
2) python cli.py --unseen_speakers p363,p364 --audio_dir $AUDIO_DIR --cache_output_dir $CACHE_DIR

**Comment by philipperemy** [comment]
Try again with the new master. I pushed the latest code.
