### ISSUE TITLE
Can anyone tell me where the namedtupled package gets?

### ISSUE THREAD

**Issue by zhangshyang** [philipperemy/deep-speaker#25]
When I run the code, I meet the problem that no module named 'namedtupled'. And I try to look for it but I can't. So if you can help me, please! Thanks!

**Comment by zhangshyang** [comment]
I have been searched for namedtupled by Baidu before, I did not find it. But I find it by Google.

**Comment by philipperemy** [comment]
```
pip install namedtupled
```

**Comment by philipperemy** [comment]
Also run
```
pip install -r requirements.txt
```
