### ISSUE TITLE
how can extract embedding from the wav?

### ISSUE THREAD

**Issue by zhangshyang** [philipperemy/deep-speaker#26]
I want to get embedding from the raw wav file which the speaker has been trained. If I remove the cache and run a cache update, then compute the embedding, the result is diffent from directly run get_embeddings command. So which one is right? And when get embedding from raw wav which not trained, the cache file need to delete every time?

**Comment by philipperemy** [comment]
Read this section in the Readme: https://github.com/philipperemy/deep-speaker#from-any-wav-files.

**Comment by philipperemy** [comment]
Deep learning is not an exact science. When you train a model, results will be different all the time.

**Comment by philipperemy** [comment]
The cache is meant to be built once. For every wav file, we extract samples randomly and place them in the cache. Once it's generated, results are fixed.
