### ISSUE TITLE
Performance of pretrained model

### ISSUE THREAD

**Issue by WIll-Xu35** [philipperemy/deep-speaker#27]
I'm working on testing the pretrained model on some public datasets. But the coding require to put every piece of audio into cache and I have to modify the code to read directly from audio file. So before doing the modification, I'd like to know the performance of the pretrianed model. If it is bad, then I would train from scratch before testing or maybe change to another approach.

Thanks.

**Comment by philipperemy** [comment]
Try again with the new master. I pushed the latest code. There is a pre-trained model already.
