### ISSUE TITLE
Where is CNN ? 

### ISSUE THREAD

**Issue by alyosama** [philipperemy/deep-speaker#29]
I have checked the paper and the code and I realized that there is no implementation for the Convolution neural networks stack such as ResNet inside the code.

**Comment by philipperemy** [comment]
@alyosama it's there: https://github.com/philipperemy/deep-speaker/tree/master/v3

But we tried it and it was too difficult to make it converge (at least not trivial). So we implemented a simpler model. The next step would be to slowly move to the CNN and ResNet.

**Comment by philipperemy** [comment]
Try again with the new master. I pushed the latest code. It's in there now!
