### ISSUE TITLE
How usable is the source code as of now ?

### ISSUE THREAD

**Issue by ad349** [philipperemy/deep-speaker#3]
Can a speaker verification model be trained now ?

**Comment by philipperemy** [comment]
@ad349 code is not usable yet. It needs to be improved. This deep speaker stuff is actually pretty hard to implement.

**Comment by prashantmaheshwari94** [comment]
+1 to the question. Can this code be used to train a model?

**Comment by philipperemy** [comment]
@prashantmaheshwari94 It's getting there. I pushed a skeleton for a v2 here:

https://github.com/philipperemy/deep-speaker/tree/master/v2

**Comment by philipperemy** [comment]
Code is usable now! I made a simpler version that seems to work great
