### ISSUE TITLE
running on ubuntu16.04 i7CPU too slow

### ISSUE THREAD

**Issue by xhsoldier** [philipperemy/deep-speaker#31]
It takes several minutes to compute the value.
May I ask what it should be? several seconds?

**Comment by xhsoldier** [comment]
any method to improve the running time?

**Comment by philipperemy** [comment]
Yeah true I'm thinking of a way to make it much faster.

**Comment by philipperemy** [comment]
Try again with the new master. I pushed the latest code. It will be much much faster.
