### ISSUE TITLE
generate_features_for_unseen_speakers target_speaker 363

### ISSUE THREAD

**Issue by amendezp** [philipperemy/deep-speaker#33]
Is there any reason why the function generate_features_for_unseen_speakers in unseen_speakers.py always uses as parameter for target speaker 'p363'?

**Comment by dmazurok** [comment]
It uses it only if you didn't provide any other value for target speaker. If you follow the code, you'll see, that it always provide the name of one of the speakers you are testing

**Comment by Aurora11111** [comment]
@amendezp  may it because of the conf.json

**Comment by philipperemy** [comment]
@amendezp  @Aurora11111 

Sorry if it was not crystal clear.

The speaker test set is defined in conf.json. I used p363 because it was the first one.

```
  "SPEAKERS_TESTING_SET": [
      "p363",
      "p364",
      "p374",
      "p376"
    ]
```

I'm going to refactor it now
