### ISSUE TITLE
Speed-up the speaker verification somehow? (Features extraction mainly)

### ISSUE THREAD

**Issue by dmazurok** [philipperemy/deep-speaker#35]
Is there any way to compute features faster? It takes around 15 minutes per speaker, or even more. Do I do anything wrong? I adapted the code, so I first make the cache, then compute features, save them to the file and only afterwards calculate the cosine simularity. But saving the features takes nearly 20 minutes per cache on i7-7700. 
Looks like the model learns during the features extraction process. I think the file should only be feed into NN without learning, and near to the finil layer the featrures are being extracted. It is different here?

**Comment by Aurora11111** [comment]
@dmazurok you shouldn't use this project's mechod to extract features ,it's really slowlly,you can reference this:https://github.com/Aurora11111/speaker-recognition-pytorch

**Comment by JpMCarrilho** [comment]
From digging a bit the code I realized that the feature generation loop is what takes a huge amount of time during the speaker comparison and embedding generation, I'm still looking into it, but changing the "max_count" variable regularizes it, can't tell you about the side effects of this though.

**Comment by philipperemy** [comment]
Try again with the new master. I pushed the latest code. It will be much much faster.
