### ISSUE TITLE
 cli.py  error

### ISSUE THREAD

**Issue by azuryl** [philipperemy/deep-speaker#37]
python cli.py --unseen_speakers p363,p363 --audio_dir $AUDIO_DIR --cache_output_dir $CACHE_DIR
2019-03-08 17:32:52,348 - INFO - audio_dir = /home/deep-speaker-data/VCTK-Corpus/
2019-03-08 17:32:52,348 - INFO - cache_dir = /home/deep-speaker-data/cache/
2019-03-08 17:32:52,348 - INFO - sample_rate = 8000
Using TensorFlow backend.
Traceback (most recent call last):
  File "cli.py", line 83, in <module>
    main()
  File "cli.py", line 71, in main
    inference_unseen_speakers(audio_reader, unseen_speakers[0], unseen_speakers[1])
  File "/home/deep-speaker/unseen_speakers.py", line 33, in inference_unseen_speakers
    sp1_feat = generate_features_for_unseen_speakers(audio_reader, target_speaker=sp1)
  File "/home/deep-speaker/unseen_speakers.py", line 22, in generate_features_for_unseen_speakers
    assert target_speaker in audio_reader.all_speaker_ids
AssertionError

**Comment by BlueAnthony** [comment]
I have the same problem.
@azuryl  Do you figure out right now?

**Comment by philipperemy** [comment]
@azuryl @BlueAnthony I'm going to add a smaller version of the dataset to make things easier.

**Comment by philipperemy** [comment]
But I can't reproduce the error. Could you reproduce all the steps of the README? Are you using v3?

https://github.com/philipperemy/deep-speaker/blob/master/README.md

**Comment by BlueAnthony** [comment]
Hi, @philipperemy, first, thank you for ur awesome work and reply.
I just follow ur guidance and use VCTK dataset, so I think I actually didn't use v3.
Somehow I fixed the problem several weeks ago.
I think I might miss some details

**Comment by Hsiny** [comment]
you should run generate command always, even just inference.
`python cli.py --regenerate_full_cache --multi_threading --cache_output_dir $CACHE_DIR --audio_dir $AUDIO_DIR
`

**Comment by philipperemy** [comment]
But did you set the variables `$AUDIO_DIR` and `$CACHE_DIR` before running the command? @Hsiny 
I re-ran all the commands and it worked great.

**Comment by Hsiny** [comment]
yes,I set the environment variables.
`update_cache  `or `regenerate_full_cache`  must be run first ,before any `unseen_speakers ` command 

It would be better add "make audio cache before inference " to documents.

reproduce the error 
just run  without any cache related command
`python cli.py --unseen_speakers p363,p364 --audio_dir $AUDIO_DIR --cache_output_dir $CACHE_DIR
`


and the right way for inference 
`python cli.py --regenerate_full_cache --multi_threading --cache_output_dir $CACHE_DIR --audio_dir $AUDIO_DIR
`
`python cli.py --unseen_speakers p363,p364 --audio_dir $AUDIO_DIR --cache_output_dir $CACHE_DIR`

or

`python cli.py --regenerate_full_cache --multi_threading --cache_output_dir $CACHE_DIR --audio_dir $AUDIO_DIR
`
`python cli.py --update_cache --multi_threading --audio_dir $NEW_AUDIO_DIR --cache_output_dir $CACHE_DIR`
`python cli.py --unseen_speakers p225,PhilippeRemy --audio_dir $NEW_AUDIO_DIR --cache_output_dir $CACHE_DIR`

**Comment by ooobsidian** [comment]
@philipperemy hello, why does it take so long to test two different speakers？
such as:
`python cli.py --unseen_speakers p363,p364 --audio_dir $AUDIO_DIR --cache_output_dir $CACHE_DIR`
it takes me ~10min, makes me anxiety.

**Comment by philipperemy** [comment]
Try again with the new master. I pushed the latest code. Should be insanely much faster and I could reproduce mostly the results of the paper.
