### ISSUE TITLE
Why is the audio truncated to max 1 seconds in next_batch.py ?

### ISSUE THREAD

**Issue by ad349** [philipperemy/deep-speaker#4]

**Comment by philipperemy** [comment]
@ad349 the code is very very alpha. It's not working correctly now! I did that to test for debugging purposes. I'd be very happy if you can contribute @ad349 :)

**Comment by shubhamaryan** [comment]
@ad349 @philipperemy All the audio samples are of variable length ranging from 1 second to 15-20 seconds. Hence, doing truncation justifies it or not?

**Comment by philipperemy** [comment]
@shubhamaryan I think it's justified to truncate somehow because you want all of them to have the same NUM_FRAMES. We can for example select 8 seconds.
For the ones less than 8 seconds, we pad them with 0 (silence).
For the ones more than 8 seconds, we truncate them.
