### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by 949371143** [philipperemy/deep-speaker#43]
[Errno 2] No such file or directory: '$CACHE_DIR\\audio_cache_pkl\\VCTK Corpus\\wav48\\p240\\p240_034_cache.pkl'

**Comment by philipperemy** [comment]
@949371143 For now it works only on linux/mac os

https://github.com/philipperemy/deep-speaker/commit/1e0b866d6290c62e6bd8f6c21bb545fc71a91768

**Comment by 949371143** [comment]
Sad story,there are many questions when it works on win7.Thank you!

**Comment by philipperemy** [comment]
Yeah don't hesitate to contribute to add support for windows if you have time!
