### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by Aurora11111** [philipperemy/deep-speaker#46]
hello,I run this project with my own datasets.but get not good result.
for same speaker(same wav have been trained) the  Cosine  = 0.0
for same speaker(different wav) the Cosine  = x*e-06 or  x*e-07
for the different speaker the Cosine  =X*e-05
there seems not much different from them ,can you give me some suggestions?

**Comment by philipperemy** [comment]
@Aurora11111 Try again with the new master. I pushed the latest code.
