### ISSUE TITLE
GPU utlization low

### ISSUE THREAD

**Issue by PBRAOS** [philipperemy/deep-speaker#48]
So i decided to go through your code which i am enjoying since yesterday! My intention is to try to help improve it and align it to the original paper.
I noticed that the utilization on my GPU is quite low close to 0% whereas my memory peaks to 8GB and i get all the relevant GPU messages from the tensorflow backend.
I also notice your comments that the code is not GPU efficient.
As you are more comfortable with the code do you think this is because when training for each "epoch" you dont really use batches of positive and negative speakers ?
Any ideas how to fix this ?

Thanks !
pb

**Comment by ooobsidian** [comment]
I have same ploblem, how to fix this? @philipperemy

**Comment by philipperemy** [comment]
Try again with the new master. I pushed the latest code.

**Comment by philipperemy** [comment]
@PBRAOS check out the latest code :)
