### ISSUE TITLE
speaker embedding

### ISSUE THREAD

**Issue by ooobsidian** [philipperemy/deep-speaker#50]
@philipperemy I want to know why cosine similarity is so close when I run `python cli.py --get_embeddings xxx --cache_output_dir $CACHE_DIR --audio_dir $AUDIO_DIR` to get two different speakers embedding?It is ~0.97, and I don't understand how to slove it.

**Comment by philipperemy** [comment]
@ooobsidian this was a simple model. Try again with the new master. I pushed the latest code.

**Comment by ooobsidian** [comment]
Thank you very much!
