### ISSUE TITLE
GPU usage rate

### ISSUE THREAD

**Issue by baobrian** [philipperemy/deep-speaker#60]
when i run train_triplet phase of this project with the enviroment ubuntu18.4 and  Tesla gpu, the nvidia-smi shows that GPU usage is only 305MiB ,i wonder how to set the gpu usage rate options in the code,thanks

**Comment by philipperemy** [comment]
Like I said, make sure that you can successful run some python scripts with tensorflow on the GPU before running deep speaker.

**Comment by philipperemy** [comment]
Let me know when you fixed it. I'll close this issue as it's non related to deep speaker.
