### ISSUE TITLE
improve test workflow

### ISSUE THREAD

**Issue by forwiat** [philipperemy/deep-speaker#65]
hello philipperemy,
Thank you so much for the great work you've shared.
I find a problem in test. when testing, the class "LazyTripletBatcher" in batcher.py still do "self.update_triplets_history()" function, which show no effect for testing and may reduce the inference speed. 
Maybe a little change will solve this.

`

class LazyTripletBatcher:

    def __init__(self, working_dir: str, max_length: int, model: etdnn, is_test=False):

        ######################

        if is_test == False:

            for _ in tqdm(range(self.history_length), desc='Initializing the batcher'):  # init history.

                self.update_triplets_history()`

**Comment by philipperemy** [comment]
@forwiat thank you so much for the feedback! Do you think you can make a small pull request to the code base?

`if is_test == False: => if not is_test:`

**Comment by forwiat** [comment]
@philipperemy yeah, I am glad to do this if I finish my work. btw, your code shows more concise.

**Comment by philipperemy** [comment]
@forwiat thank you!

**Comment by philipperemy** [comment]
So I had a look and it's just in the initialization. It does not slow down the training speed as it is run only once. So no problem ;)
