### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by mapledxf** [philipperemy/deep-speaker#66]
Hello there,
I was trying to read the code, and got confused with this line:
https://github.com/philipperemy/deep-speaker/blob/cc1a90baca155da824603f59bb3d54cef86f2152/conv_models.py#L61

what does 512 mean? is it the num of speakers?

**Comment by philipperemy** [comment]
@mapledxf no it's the length of the embeddings vectors. It can be of any arbitrary value and does not depend on the number of speakers.

**Comment by mapledxf** [comment]
@philipperemy  got it, thx
