### ISSUE TITLE
How can I continue training with my own dataset

### ISSUE THREAD

**Issue by VinhDevNguyen** [philipperemy/deep-speaker#67]
Hi, Is it possible if I use your pretrained model to continue training with my own dataset? If it possible can you show me how to do that? Thanks !!!

**Comment by philipperemy** [comment]
@VinhDevNguyen yes def possible! All you need is to have the same format as the LibriSpeech dataset.
Just create a big folder, and speakers as sub folders and put your wav/flac files in there.
Then rebuild your caches: https://github.com/philipperemy/deep-speaker/blob/cc1a90baca155da824603f59bb3d54cef86f2152/deep-speaker#L29.
And I think you can restart the commands and should work!

**Comment by VinhDevNguyen** [comment]
Thank you so much! I will try it ;)

**Comment by philipperemy** [comment]
Let me know ;)
