### ISSUE TITLE
What are the datasets used to train the model?

### ISSUE THREAD

**Issue by askaydevs** [philipperemy/deep-speaker#68]
In the paper, I found the mention of a dataset called UIDs, but the released model is trained on LibriSpeech. I am assuming that the UIDs dataset is not available publicly. In the paper, the two datasets consisted of Mandarine speech, and another one was English speech.

**Question**: Does the model work _better_ for Mandarine speech or on English speech. Or the language doesn't affect the model performance?

**Comment by philipperemy** [comment]
Well I guess as long as you have a sufficiently big dataset, the language should not matter.

**Comment by philipperemy** [comment]
The datasets Baidu used are proprietary.

**Comment by askaydevs** [comment]
Thanks.
