### ISSUE TITLE
Cannot load pretrained weights

### ISSUE THREAD

**Issue by Yuvaraj91** [philipperemy/deep-speaker#71]
I am trying  to load the pretrained weights
` model.m.load_weights('ResCNN_triplet_training_checkpoint_265.h5', by_name=True)`

but i get this error: AttributeError: 'str' object has no attribute 'decode'. I have installed the same versions for all libraries, and tried some workarounds after googling. Anyone faced and managed to fix this issue?

**Comment by philipperemy** [comment]
@Yuvaraj91 it's a regression in `h5py`: https://github.com/tensorflow/tensorflow/issues/44467.
Solution is to run `pip install 'h5py < 3.0.0'`.
I updated the requirements.
