### ISSUE TITLE
average embeddings

### ISSUE THREAD

**Issue by taalua** [philipperemy/deep-speaker#74]
Hi, thanks for the code.
How to average embeddings?
I follow this code in previous issues, but it won't sum to 1.0 after np.mean.

def embedding_average(path, model):
    audio_list = os.listdir(path)
    sum = []
    for idx, audio in enumerate(audio_list):
        tmp = get_per_speaker_embedding(path + '/' + audio, model)
        sum.append(tmp)
    return np.mean(sum, axis=0)

**Comment by philipperemy** [comment]
@taalua it should not sum to 1. Embeddings are defined on a hypersphere where their L2 norm is 1.

![image](https://user-images.githubusercontent.com/4516927/106066125-a2608300-613f-11eb-86cb-87198f31cf87.png)


For every embedding (if I refer to the example in the README), the L2 norm computed by this function should be equal to 1:

```python
np.sqrt(np.sum(predict_001 ** 2)) # will be equal to 1.
```

When we train, the normalization is done here: https://github.com/philipperemy/deep-speaker/blob/cd354a761eb0b111bc29a0d2f7f0806f94e07fd5/conv_models.py#L67

If you want to average N embedding, I guess they are many ways to do it. But you can take the mean embedding and then normalize it by the L2 norm `(np.sqrt(np.sum(v**2))`.

**Comment by taalua** [comment]
Thanks for quick reply!
