### ISSUE TITLE
Error：SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mocaibupt** [philipperemy/deep-speaker#75]
when i use:
`python example.py`
The terminart:
```
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    from audio import read_mfcc
  File "/home/aaa/SpeakerRecongnize/deep-speaker/audio.py", line 11, in <module>
    from constants import SAMPLE_RATE, NUM_FBANKS
ImportError: cannot import name 'SAMPLE_RATE' from 'scipy.optimize._highs.constants' (/home/aaa/.conda/envs/dspeaker-py37/lib/python3.7/site-packages/scipy/optimize/_highs/constants.cpython-37m-x86_64-linux-gnu.so)
```
I think it's perssmision question.So I use:
`sudo python example.py`
but there incur:
```
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    from audio import read_mfcc
  File "/home/aaa/SpeakerRecongnize/deep-speaker/audio.py", line 30
    def extract_speaker_and_utterance_ids(filename:str):  # LIBRI.
                                                  ^
SyntaxError: invalid syntax
```

**Comment by philipperemy** [comment]
Use python3.6 or above.

**Comment by mocaibupt** [comment]
> Use python3.6 or above.

I used python3.7，I don't know why。I have searchen it in web before I ask it ,but there are no correct solution.So Can you give me some guide?Thanks very much.

**Comment by philipperemy** [comment]
@mocaibupt sorry I didn't see your first error. I updated the `requirements.txt`.

It means that scipy 1.6.0 has a bug. So either run:

```
pip install -r requirements.txt --upgrade
```

Or downgrade scipy:
```
scipy<1.6.0
```

**Comment by mocaibupt** [comment]
> @mocaibupt sorry I didn't see your first error. I updated the `requirements.txt` in the repo. It was effectively a bug I found today.
> 
> Scipy 1.6.0 has a bug. So either run:
> 
> ```
> pip install -r requirements.txt --upgrade
> ```
> 
> Or downgrade scipy:
> 
> ```
> scipy<1.6.0
> ```
> 
> Do not use sudo python because it is probably the python2.7 packaged with your system.
> 
> This should solve your problems.

I am sorry to interupt you again.I am the project master student.I haven't been exposed to voiceprint recognition before, but now I apply a voiceprint recognition to my graduation project。

I want to know something about the ResCNN Softmax+Triplet trained model：

1.The different between ResCNN and ResNet（I know what is CNN and what is ResNet,but I do not know ResCNN)

2. Is the Triplet mean Triplet Loss?

Thank you very much

**Comment by philipperemy** [comment]
1. ResCNN = Residual CNN = ResNet + Convolutional layers (it is a mix).
2. Yes Triplet means Triplet Loss.
