### ISSUE TITLE
pretraind model cannot download

### ISSUE THREAD

**Issue by wenku1992abc** [philipperemy/deep-speaker#77]
https://drive.google.com/file/d/1F9NvdrarWZNktdX9KlRYWWHDwRkip_aP.

we cannot visit this link~  do you have any other method to vist?

**Comment by philipperemy** [comment]
What do you suggest?

**Comment by philipperemy** [comment]
![image](https://user-images.githubusercontent.com/4516927/113293351-9c01a980-9330-11eb-8458-9d4f437980b5.png)

https://www.weiyun.com/

Can you access?

**Comment by wenku1992abc** [comment]
> https://share.weiyun.com/V2suEUVh
> 
> Can you access?

yes,i can 
thanks very very much!

**Comment by philipperemy** [comment]
Great!
