### ISSUE TITLE
ValueError: Cannot take a larger sample than population when 'replace=False'

### ISSUE THREAD

**Issue by wenku1992abc** [philipperemy/deep-speaker#80]
hi,sorry to bother you again~

when i run :_python cli.py train-model --working_dir "${TRIPLET_TRAINING_WORKING_DIR}"_

there is such error:

- Traceback (most recent call last):
-   File "cli.py", line 101, in <module>
-     cli()
-   File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
-     return self.main(*args, **kwargs)
-   File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
-     rv = self.invoke(ctx)
-   File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
-     return _process_result(sub_ctx.command.invoke(sub_ctx))
-   File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
-     return ctx.invoke(self.callback, **ctx.params)
-   File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
-     return callback(*args, **kwargs)
-   File "cli.py", line 97, in train_model
-     start_training(working_dir, pre_training_phase)
-   File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/train.py", line 109, in start_training
-     fit_model(dsm, working_dir, NUM_FRAMES)
-   File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/train.py", line 21, in fit_model
-     batcher = LazyTripletBatcher(working_dir, max_length, dsm)
-   File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/batcher.py", line 154, in __init__
-     self.update_triplets_history()
-   File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/batcher.py", line 165, in update_triplets_history
-     for selected_utterance in np.random.choice(a=train_utterances, size=self.nb_per_speaker, replace=False):
-   File "mtrand.pyx", line 1168, in mtrand.RandomState.choice
- **ValueError: Cannot take a larger sample than population when 'replace=False'
-**

**Comment by philipperemy** [comment]
Ah seems like your data is incomplete. You probably have some speakers which contain only one or two utterances and that's why it fails. On the datasets, I was training on, each speaker had like 500 utterances.


```
/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/batcher.py Line 165
```
You can add to understand:

```python
print(train_utterances)
print(self.nb_per_speaker)
for selected_utterance in np.random.choice(a=train_utterances, size=self.nb_per_speaker, replace=False):
```

**Comment by wenku1992abc** [comment]
@philipperemy 
i am sorry for taking a long time to reply to you !

thanks,I tried  
it is 'train_utterances' who is null []
so i add lines in /raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/batcher.py Line 165
```
if len(train_utterances) != 0:
                for selected_utterance in np.random.choice(a=train_utterances, size=self.nb_per_speaker, replace=False):
```
but new error occurs:

> Initializing the batcher:   0%|                                                                                                                        | 0/4 [00:10<?, ?it/s]
> Traceback (most recent call last):
>   File "cli.py", line 101, in <module>
>     cli()
>   File "/home/user9/anaconda3/envs/bob_env1/lib/python3.7/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/user9/anaconda3/envs/bob_env1/lib/python3.7/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/user9/anaconda3/envs/bob_env1/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/user9/anaconda3/envs/bob_env1/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/user9/anaconda3/envs/bob_env1/lib/python3.7/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "cli.py", line 97, in train_model
>     start_training(working_dir, pre_training_phase)
>   File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/train.py", line 109, in start_training
>     fit_model(dsm, working_dir, NUM_FRAMES)
>   File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/train.py", line 21, in fit_model
>     batcher = LazyTripletBatcher(working_dir, max_length, dsm)
>   File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/batcher.py", line 154, in __init__
>     self.update_triplets_history()
>   File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/batcher.py", line 171, in update_triplets_history
>     embeddings = np.reshape(embeddings, (len(selected_speakers), self.nb_per_speaker, 512))
>   File "<__array_function__ internals>", line 6, in reshape
>   File "/home/user9/anaconda3/envs/bob_env1/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
>     return _wrapfunc(a, 'reshape', newshape, order=order)
>   File "/home/user9/anaconda3/envs/bob_env1/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
>     return bound(*args, **kwds)
> **ValueError: cannot reshape array of size 654336 into shape (640,2,512)**
> 


by the way ,when i train triplet,why no need to change the data to keras input?

**Comment by wenku1992abc** [comment]
pip uninstall -y tensorflow && pip install tensorflow-gpu
./deep-speaker download_librispeech    # if the download is too slow, consider replacing [wget] by [axel -n 10 -a] in download_librispeech.sh.
./deep-speaker build_mfcc              # will build MFCC for softmax pre-training and triplet training.
.**/deep-speaker build_model_inputs      # will build inputs for softmax pre-training.**
./deep-speaker train_softmax           # takes ~3 days.
./deep-speaker train_triplet           # takes ~3 days.


i followed this instruction

- /deep-speaker build_model_inputs 

     # will build inputs for softmax pre-training

this line ,it just build inputs for softmax pre-training,not for triplet training?

**Comment by philipperemy** [comment]
```
ValueError: cannot reshape array of size 654336 into shape (640,2,512)
```

It seems like we want to have 640 speakers with 512 embeddings each. In your code, you might not have 640 speakers. That's maybe why you have this error?

> by the way ,when i train triplet,why no need to change the data to keras input?
The keras input was only used for the softmax-pretraining. The triplet generates inputs in real time.
`/deep-speaker build_model_inputs` only builds input for softmax pre-training yes.

In 2018/2019, Keras did not have the support of triplet training. I think it's 2021, it does now.

**Comment by wenku1992abc** [comment]
@philipperemy 
ok, thanks,i will check it out

**Comment by kli017** [comment]
@wenku1992abc hello have you solved this problem? I met the same error when I train on CN-Cele Dataset

**Comment by philipperemy** [comment]
@kli017 `Cannot take a larger sample than population when 'replace=False'` if you get this error, that means your data is not properly loaded. The python script does not see any files.

**Comment by kli017** [comment]
@philipperemy Thanks for the remind! I checked the data and found there some speaker only have 1 audio file and cause this problem.

**Comment by philipperemy** [comment]
@kli017 great to hear
