### ISSUE TITLE
Different source of audio

### ISSUE THREAD

**Issue by EhsanAlahi** [philipperemy/deep-speaker#81]
The model works fine on audio samples recorded from the same device ( headset) but when I calculate the embedding similarity of two audio samples recorded with different devices ( clear background/ no noise ), the model fails badly.  I am looking for a suggestion on how to handle this issue. can we add some preprocessing stage for these audio samples? 
Thanks and Regards.

**Comment by philipperemy** [comment]
@EhsanAlahi, try to match as much as possible the audio the model was trained on (clear speech LibriSpeech).
That means absolutely no noise, distortion, or background noise. What we should ideally is retraining the model by adding more noise but that's not easy. In your case, use VAD (Voice Activity Detection) as pre-processing and only select the parts that have clear speech. Strip the blank and the silences. The model was not trained on them.
