### ISSUE TITLE
how to save enroll file in encrypted mode and decrypted for matching  how ?

### ISSUE THREAD

**Issue by Adarsh474532** [philipperemy/deep-speaker#91]

**Comment by philipperemy** [comment]
I don't understand your question. Can you reformulate it?

**Comment by Adarsh474532** [comment]
ok, 
import pyaudio
import wave
import cv2
import os
import pickle
import time
from scipy.io.wavfile import read
from IPython.display import Audio, display, clear_output

FORMAT = pyaudio.paInt16
CHANNELS = 2
RATE = 44100
CHUNK = 1024
RECORD_SECONDS = 15
FILENAME = "D:/trs/deep-speaker-master/Database/Candiate_22/enroll.wav"

audio = pyaudio.PyAudio()
   
    # start Recording
stream = audio.open(format=FORMAT, channels=CHANNELS,
                    
                    rate=RATE, input=True,
                    frames_per_buffer=CHUNK)

time.sleep(2.0)
print("recording...")
frames = []

for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
    data = stream.read(CHUNK)
    frames.append(data)
print("finished recording")
    # stop Recording
stream.stop_stream()
stream.close()
audio.terminate()

    # saving wav file 
waveFile = wave.open(FILENAME, 'wb')
waveFile.setnchannels(CHANNELS)
waveFile.setsampwidth(audio.get_sample_size(FORMAT))
waveFile.setframerate(RATE)
waveFile.writeframes(b''.join(frames))
waveFile.close()

**Comment by Adarsh474532** [comment]
i am saving the file in enroll.wav and in the verification time match the enroll.wav and test.wav.
 My question is how to save enroll.wav in any db and verified time fetch the same format.

**Comment by Adarsh474532** [comment]
like voice print file save anywhere and decrypt for matching.

**Comment by philipperemy** [comment]
@Adarsh474532 I'm not sure I understand your question.
