### ISSUE TITLE
impact of using delta, trim_silence in training

### ISSUE THREAD

**Issue by zabir-nabil** [philipperemy/deep-speaker#92]
HI,
I see you removed the delta features and trimming silence from the training code. Did you experiment with that? Is it worth it using them?

**Comment by philipperemy** [comment]
@zabir-nabil I don't think they were using it in the paper. That's why I removed them. I haven't tried to see if it had any value but I can bet it does.

**Comment by philipperemy** [comment]
Trimming silence is a must I guess. I think it's done in the code (with a simple VAD technique)
