### ISSUE TITLE
Embedding/Identifying a speaker talking in a different language with pretrained model

### ISSUE THREAD

**Issue by jinny1208** [philipperemy/deep-speaker#93]
Hi, I am in the middle of reading your paper and studying your code so I may be asking an irrelevant question, but
is it possible to create a speaker embedding from a speaker that is talking in a different language using your pretrained model?

Thanks in advance

**Comment by philipperemy** [comment]
Hey, results will be much better in english. If you want to use it in a different language, you have to re-train it.
