### ISSUE TITLE
How to compute between model and audo file ?

### ISSUE THREAD

**Issue by TonyB22** [philipperemy/deep-speaker#94]
Hello , 

This example compute just between 2 audio files  . 

But what if I want to train model with 5 audio files that belongs to 1 speaker, and then just check another audio file with this speaker ?

I mean , I just want to compute 1 audo file with speaker ID that already exists in model 

Please help !
Thanks
Tony

**Comment by philipperemy** [comment]
Hello,

You can't train the model with just one speaker.

The model was trained with thousands of speakers. The idea is that you don't really need to train another model. But it was trained on english so if you want to use any other language, you might have to re-train it on a large dataset.

The example compares 2 audio files. You can always compare one audio file with many others. Like 1 and 5. You just make a for loop for that. And take either the min or max score among the 5 comparisons.

**Comment by TonyB22** [comment]
Dear Philip , 

Thank you very much for your answer . 

if you don't mind, I would like to ask one more question 

For example I have trained a new model on another language with thousands of speakers.

One of this speakers is Bob with 5 wav files.

1.wav  = 30seconds
2.wav  = 30seconds
3.wav  = 30seconds
4.wav  = 30seconds
5.wav  = 30seconds

After I have built model , I have received one more Bob's voice 6.wav = 2mins .

After that I have received one more unknown wav file and I want to check is it Bob or not . (unknown.wav)

What will be better , to compare unknown.wav with 6.wav (not trained file) , or it will be better to compare with already trained (1,2,3,4,5) wav files to get better results ?

Will trained files get better results ? or is it same ?

Thank you very much

**Comment by philipperemy** [comment]
It will always be more precise to compare unknown.wav with 1.wav,2.wav,3.wav,4.wav,5.wav.

Even though the model was trained on Bob, 6.wav was never seen by the model (during training). So the error may be slightly higher (not always the case but almost surely).

Ideally, it should be the same (6.wav or using 1/2/3/4/5.wav). Your intuition is right. But in practice, using data from the training set will always bring better results.

**Comment by TonyB22** [comment]
Thank you very much for your answers ! 

If you don't mind , I would like to ask 2 more questions . 

1) What is the best length for audio file to train to get best results ? I mean , how much seconds should be audio files that I am planning to train ?

2) Also , what is the best length to check 2 files ? how much seconds should be audio files for checking to get the best results ?

**Comment by philipperemy** [comment]
@TonyB22 the model was trained on this dataset: http://www.openslr.org/12.

Here is an example: https://github.com/philipperemy/deep-speaker/blob/master/samples/1255-90413-0001.flac.

This one is 7-second long. But I think anything between 3 and 7 should work well. 1 second might be too short.

To check between 2 files, it's better that they match the same duration as the ones the model was trained on. So again around 3~7 seconds should work well!

PS: Make sure there is no background noise.

**Comment by TonyB22** [comment]
Dear Philip, 
Thank you very much for you answers . You are very kind. 

I would like to ask my last question . 

For example I have audio file with 30 seconds duration

First 10 seconds speaks Tom
Second 10 seconds speaks Bob
Third 10 seconds speaks John

I would like to make "Speaker Diarization" and cut this audio file to 3 parts . 

Can you please advice me any project for doing this job ? with example codes like your project. 

I am very thankful to you for your great project "Speaker verification" . 

I have searched all internet for speaker verification and yours is the best !

**Comment by philipperemy** [comment]
@TonyB22 happy to hear that!!

I implemented a paper about speaker change detection: https://github.com/philipperemy/speaker-change-detection.

But it's less "ready to use" than this deep speaker repository.

However with a bit of tweaking, it should do the job. I can provide some help if needed.

Good luck!

**Comment by TonyB22** [comment]
@philipperemy Thank you very much ! 

I have already started download process and will start training process soon .. 

I will come back to you once I will finish train process .. 

But I see there is no example codes for checking speaker change . Where can I find example codes ?

In Speaker Verification project you have example codes and that is perfect !

Thank you !

**Comment by philipperemy** [comment]
@TonyB22 yeah the speaker detection project is more experimental/research focused. It is less "ready to use".
