### ISSUE TITLE
ValueError: "Tensor is not an element of this graph" when using TripletBatcherMiner during Triplet training

### ISSUE THREAD

**Issue by Franek18** [philipperemy/deep-speaker#98]
Hi,
instead of using LazyTripletBatcher I tried to use TripletBatcherMiner, which is implemented in batcher.py, because it is recommended during Triplet training to use online mining. But I struggle with the following error:

> ValueError: Tensor Tensor("loss/AddN_1:0", shape=(), dtype=float32) is not an element of this graph.

which occures during executing this line of code in class TripletBatcherMiner:
`loss = self.model.m.evaluate(bx, by, batch_size=batch_size, verbose=0)`

I don't understand why this is happening, the same model is trained and used to evaluate samples in batch according to the original implementation. I didn't change anything in the code. I am confused as this problem is popular when using more than one model in the same Tensorflow session, but only one model is used here and actually for the same ...
Have you ever tried training a model with this approach, caught this problem and found a workaround?

Regards
Franek

**Comment by Franek18** [comment]
I am using

- Python 3.8.13
- keras==2.9.0
- tensorflow-gpu==2.9.1

**Comment by philipperemy** [comment]
@Franek18 It seems like this `TripletBatcherMiner` is using a `Loss` that is not part of the current model / checkpoints. It is probably something that was used in the past but has not been updated with the latest model code.

**Comment by Franek18** [comment]
@philipperemy Thank for your answer. `TripletBatcherMiner` doesn't make any modifications in the model.
The code of this pipeline is as follows:
I am using original code for training with Triplet loss in file train.py:
```python
       logger.info('Training with the triplet loss.') 
        dsm = DeepSpeakerModel(batch_input_shape, include_softmax=False)
        triplet_checkpoint = load_best_checkpoint(CHECKPOINTS_TRIPLET_DIR)
        pre_training_checkpoint = load_best_checkpoint(CHECKPOINTS_SOFTMAX_DIR)
        if triplet_checkpoint is not None:
            logger.info(f'Loading triplet checkpoint: {triplet_checkpoint}.')
            dsm.m.load_weights(triplet_checkpoint)
        elif pre_training_checkpoint is not None:
            logger.info(f'Loading pre-training checkpoint: {pre_training_checkpoint}.')

            dsm.m.load_weights(pre_training_checkpoint, by_name=True)
        dsm.m.compile(optimizer=SGD(), loss=deep_speaker_loss)

        # Here I am calling a new function, which uses TripletBatcherMiner instead of LazyTripletBatcher
        fit_model_triplet_miner(dsm, working_dir, kc.kx_train, kc.ky_train, kc.kx_test, kc.ky_test)
```
The code of this function is as follows:
```python
def fit_model_triplet_miner(dsm: DeepSpeakerModel, working_dir, kx_train,
                            ky_train, kx_test, ky_test, max_length: int = NUM_FRAMES, batch_size=BATCH_SIZE):
   # Here I am passing the same model dsm to the TripletBatcherMiner which is going to be train
    batcher = TripletBatcherMiner(kx_train, ky_train, kx_test, ky_test, dsm)

    # build small test set.
    test_batches = []
    for _ in tqdm(range(200), desc='Build test set'):
        test_batches.append(batcher.get_batch(batch_size, is_test=True))

    def test_generator():
        while True:
            for bb in test_batches:
                yield bb

    def train_generator():
        while True:
            yield batcher.get_batch(batch_size, is_test=False)

    checkpoint_name = dsm.m.name + '_lowpassnoise' + '_checkpoint'
    checkpoint_filename = os.path.join(CHECKPOINTS_TRIPLET_DIR, checkpoint_name + '_{epoch}.h5')
    checkpoint = ModelCheckpoint(monitor='val_loss', filepath=checkpoint_filename, save_best_only=True)
    dsm.m.fit(x=train_generator(), y=None, steps_per_epoch=2000, shuffle=False,
             epochs=1000, validation_data=test_generator(), validation_steps=len(test_batches),
             callbacks=[checkpoint])
```
And the code of the TripletBatcherMiner is as follows:
```python
class TripletBatcherMiner(TripletBatcher):

    def __init__(self, kx_train, ky_train, kx_test, ky_test, model: DeepSpeakerModel):
        super().__init__(kx_train, ky_train, kx_test, ky_test)
        self.model = model
        self.num_evaluations_to_find_best_batch = 10

    def get_batch(self, batch_size, is_test=False):
        if is_test:
            return super().get_batch(batch_size, is_test)
        max_loss = 0
        max_batch = None, None
        for i in range(self.num_evaluations_to_find_best_batch):
            bx, by = super().get_batch(batch_size, is_test=False)  # only train here.
            loss = self.model.m.evaluate(bx, by, batch_size=batch_size, verbose=0) # <- This is the line which  causes an error
            if loss > max_loss:
                max_loss = loss
                max_batch = bx, by
        return max_batch
```
Of course BatcherMiner is working on Keras Inputs instead of audio-fbanks, but I didn't change a compiler of a dsm, it is `optimizer=SGD(), loss=deep_speaker_loss`.
@philipperemy Do you mean that you haven't used an online mining for Triplet training and relies only on LazyTriplet?
I'm asking because LazyTriplet gives us very poor results and it's a common approach to use an online mining triplet.

**Comment by philipperemy** [comment]
I'll take more time to answer you later but for the model I did one training with a softmax (pre-training) and a second training on top of it to select the hard examples to lower the loss even more. It was the methodology described in the paper. What is `LazyTriplet` doing? I forgot.

**Comment by Franek18** [comment]
`LazyTriplet` is only using a model during the initialization of it's object to evaluate triplet's pairs before the training. So it's evaluation is TBH completely useless and that's why I would like to use online mining.
What do you exactly mean by `selecting hard examples`? Did you do it with a class `TripletBatcherSelectHardNegatives` or in a different way?
Regards

**Comment by philipperemy** [comment]
I read the code again. So `LazyTriplet` keeps a history buffer that is updated every X epochs during training. And it seems like, in this history buffer, the best triplets are selected based on the cosine similarity (get_batch_train). I am pretty sure that's the batcher used in the last training. The loss EER was 0.043 with just pre-training and went down to 0.025 with this batcher. Lazy just means that the audio files are loaded on demand and not cached in memory.

> Softmax pretraining has a poor ability to selecting a proper AN, AP pairs and that's why I would like to use online mining. 

Yes it's correct.

> selecting hard examples

From my memory, in the paper they define hard example like that: take a triple (A, P, N). Define d(A,P)-d(A,N) or the opposite I forgot. This difference has to be greater than an alpha = 0.1. Otherwise P is too similar to N and the model does not learn.

I think the class `TripletBatcherSelectHardNegatives` was just a milestone and has never been used to train anything. Probably because it was too slow because either all the audio dataset has to be loaded in memory or it was too slow to read each audio file at every batch. That's why a history buffer was introduced. I think they mentioned it in the paper too.
